// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDboeU1DMXjXuFkZgNxayKV7z0YBnd7vgs',
    appId: '1:1056309293294:web:73d440634f2e7aba7943ff',
    messagingSenderId: '1056309293294',
    projectId: 'my-chat-ce780',
    authDomain: 'my-chat-ce780.firebaseapp.com',
    storageBucket: 'my-chat-ce780.appspot.com',
    measurementId: 'G-MXJTDQTVL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeysuzS5nAKymcPXwEfGBcQNe3Q6u41hs',
    appId: '1:1056309293294:android:50dc33943c9c472a7943ff',
    messagingSenderId: '1056309293294',
    projectId: 'my-chat-ce780',
    storageBucket: 'my-chat-ce780.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAj31efplrgEzLIHMp1ol3LQg9iK0vv20',
    appId: '1:1056309293294:ios:01fd8b9445e48e127943ff',
    messagingSenderId: '1056309293294',
    projectId: 'my-chat-ce780',
    storageBucket: 'my-chat-ce780.appspot.com',
    iosBundleId: 'com.example.chatApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAj31efplrgEzLIHMp1ol3LQg9iK0vv20',
    appId: '1:1056309293294:ios:01fd8b9445e48e127943ff',
    messagingSenderId: '1056309293294',
    projectId: 'my-chat-ce780',
    storageBucket: 'my-chat-ce780.appspot.com',
    iosBundleId: 'com.example.chatApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDboeU1DMXjXuFkZgNxayKV7z0YBnd7vgs',
    appId: '1:1056309293294:web:700a9218506c5a137943ff',
    messagingSenderId: '1056309293294',
    projectId: 'my-chat-ce780',
    authDomain: 'my-chat-ce780.firebaseapp.com',
    storageBucket: 'my-chat-ce780.appspot.com',
    measurementId: 'G-LS7K9PJSX6',
  );
}
